server:
  port: "8080"
  name: tools-admin
  mode: "debug"
  jwt_secret: "your-secret-key"
  jwt_expire: 86400 # 24小时

logger:
  level: debug
  path: ./logs/
  max_age: 7

db:
  host: 127.0.0.1
  port: 13306
  username: root
  password: 123456
  database: tools_admin
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

redis:
  host: 127.0.0.1
  port: 16379
  password: 123456
  db: 0
  pool_size: 100
